#' Logical Dataframe Coordinates Heatmap
#'
#' @description
#' Perform the logical searching of \code{\link{which.coord}}, and plot the
#' results as a NMF package based heatmap.
#'
#' @inheritParams which.coord
#' @inheritDotParams NMF::aheatmap
#'
#' @return A plot generated by \code{\link[NMF]{aheatmap}} showing in red the
#' coordinates of the found matches.
#'
#' @importFrom NMF aheatmap
#'
#' @export heatmap.coord
#'
heatmap.coord <- function(data, bool = NULL, mode = "isnot.na", ...) {
  lo <- mistats::which.coord(data = data, bool = bool, mode = mode)  # lo -> list object

  if (is.null(lo)) {NULL; cat("No results found. No plot generated.\n")}
  else {
    df <- data.frame()
    for (i in 1:nrow(lo)) {
      df[lo[i, "rowname"], lo[i, "colname"]] <- 1
    }
    df[is.na(df)] <- 0

    NMF::aheatmap(df, ...)
  }
}

