#' Logical Dataframe Coordinates Heatmap
#'
#' @description
#' Perform the logical searching of \code{\link{which.coord}}, and plot the
#' results as a NMF package based heatmap.
#'
#' @inheritParams which.coord
#' @param value
#' If TRUE, original values are represented in the heatmap. If FALSE (default),
#' matched cells are set to 1, and unmatched cells to 0.
#' @param as.table
#' If TRUE, function returns the \code{data.frame} which the plot is based on.
#' @inheritDotParams NMF::aheatmap
#'
#' @return A plot generated by \code{\link[NMF]{aheatmap}} showing in red the
#' coordinates of the found matches.
#'
#' @importFrom NMF aheatmap
#'
#' @export heatmap.coord
#'
heatmap.coord <- function(data, bool = NULL, mode = "isnot.na", value = FALSE, as.table = FALSE, ...) {
  lo <- mistats::which.coord(data = data, bool = bool, mode = mode)  # lo -> list object

  if (is.null(lo)) {cat("No results found. No plot generated.\n"); NULL}
  else {
    df <- data.frame()

    if (value) {
      mtext <- data.frame()
      for (i in 1:nrow(lo)) {
        df[lo[i, "rowname"], lo[i, "colname"]] <- lo[i, "value"]
        mtext[lo[i, "rowname"], lo[i, "colname"]] <- signif(lo[i, "value"],
                                                            digits = 5)
      }
      if (length(unique(unlist(c(df)))) == 1) {
        NMF::aheatmap(df, txt = mtext, Rowv = NA, Colv = NA, breaks =2, ...)
        if (as.table) df
      }
      else {
        NMF::aheatmap(df, txt = mtext, Rowv = NA, Colv = NA, ...)
        if (as.table) df
      }
    }

    else {
      for (i in 1:nrow(lo)) {
        df[lo[i, "rowname"], lo[i, "colname"]] <- 1
      }
      df[is.na(df)] <- 0

      if (length(unique(unlist(c(df)))) == 1) {
        NMF::aheatmap(df, Rowv = NA, Colv = NA, breaks = 2, ...)
        if (as.table) df
      }
      else {
        NMF::aheatmap(df, Rowv = NA, Colv = NA, ...)
        if (as.table) df
      }
    }
  }
}
