#' Logical Dataframe Coordinates Heatmap
#'
#' @description
#' Perform the logical searching of \code{\link{which.coord}}, and plot the
#' results as a NMF package based heatmap.
#'
#' @inheritParams which.coord
#' @param value
#' If TRUE, original values are represented in the heatmap. If FALSE (default),
#' matched cells are set to 1, and unmatched cells to 0.
#' @inheritDotParams NMF::aheatmap
#'
#' @return A plot generated by \code{\link[NMF]{aheatmap}} showing in red the
#' coordinates of the found matches.
#'
#' @importFrom NMF aheatmap
#'
#' @export heatmap.coord
#'
heatmap.coord <- function(data, bool = NULL, mode = "isnot.na", value = FALSE, ...) {
  lo <- mistats::which.coord(data = data, bool = bool, mode = mode)  # lo -> list object

  if (is.null(lo)) {NULL; cat("No results found. No plot generated.\n")}
  else {
    df <- data.frame()

    if (value) {
      mtext <- data.frame()
      for (i in 1:nrow(lo)) {
        df[lo[i, "rowname"], lo[i, "colname"]] <- lo[i, "value"]
        mtext[lo[i, "rowname"], lo[i, "colname"]] <- lo[i, "value"]
      }
      NMF::aheatmap(df, txt = mtext, Rowv = NA, Colv = NA, ...)
    }

    else {
      for (i in 1:nrow(lo)) {
        df[lo[i, "rowname"], lo[i, "colname"]] <- 1
      }
      df[is.na(df)] <- 0
      NMF::aheatmap(df, Rowv = NA, Colv = NA, ...)
    }
  }
}

